config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "employees#index"
 post '/employees/fetch_employee_data', to: 'employees#fetch_employee_data'
  resources :employees, except: [:index] do
    collection do
      get :myemployees
    end
    resources :appointments, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  resources :appointments, only: [:index, :show, :destroy] do
    collection do
      get :historic
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_one_attached :avatar
  belongs_to :user  # géré par as_owner ?
  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validates :job_title, length: { minimum: 4 }, presence: true
  validates :description, length: { minimum: 6 }
  validates :price_per_day, numericality: { only_integer: true }, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :appointments
  has_many :employees
  has_many :appointments_as_owner, through: :employees, source: :appointments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:destroy]

  def index
    @appointments = Appointment.where(user: current_user)
  end

  def new
    @employee = Employee.find(params[:id])
    @appointment = Appointment.new
  end


  def create

    @employee = Employee.find(params[:employee_id])
    @appointment = Appointment.new(appointments_params)
    @appointment.user = current_user
    @appointment.employee = @employee
    @appointment.save!
    if @appointment.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    if @appointment.destroy
      redirect_to employees_path(@appointment.employee), status: :see_other
    else
      render :index, status: :unprocessable_entity
    end
  end


  def historic
     @appointments = Appointment.where(user: current_user)
  end

private

  def appointments_params
    params.require(:appointment).permit(:total_price, :renting_days,  :debut_de_reservation, :fin_de_reservation)
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/employees_controller.rb
require "open-uri"

class EmployeesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_employee, only: [:edit, :update, :destroy]

  def index
    @employees = Employee.all
    @top_employees = @employees.sort_by do |employee|
      if employee[:rating]
          -employee[:rating]
      end
    end
    @top_employees = @top_employees[0, 3]
    @employee_roulette

    employee_name = params[:data]
    @employee_roulette = Employee.find_by(job_title: employee_name)

    if params[:query].present?
      sql_query = "job_title ILIKE :query OR first_name ILIKE :query OR last_name ILIKE :query"
      @search_employees = Employee.where(sql_query, query: "%#{params[:query]}%")
    else
      @search_employees = Employee.all
    end


  respond_to do | format |
    format.html
      format.text do
        render partial: "top", locals: { top_employees: @search_employees }, formats: :html
      end
    end
  end


 def fetch_employee_data
    employee_name = params[:data]
    puts '----------------------------'
    puts employee_name
    puts '----------------------------'
    employee = Employee.find_by(job_title: employee_name)
    render json: { employee: employee }
  end


  def show
    @employee = Employee.find(params[:id])
    @appointment = Appointment.new
    @reviews = Review.where(employee: params[:id])
    @review = Review.new
    total_rating = 0
    if @reviews.present?
      @reviews.each do |review|
        total_rating += review.rating
      end
      @average_rating = (total_rating / @reviews.count).round
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.rating = 0
    @employee.avatar.attach(io: URI.open(params[:employee][:avatar]), filename: "jean.jpg", content_type: "image/jpg")
    # @employee.avatar.attach(io: URI.open(), filename: "jean.jpg", content_type: "image/jpg")
    @employee.user = current_user
    if @employee.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    puts "coucou"
  end

  def update
    # @employee.avatar.attach(io: URI.open(params[:employee][:avatar]), filename: "jean.jpg", content_type: "image/jpg")
    if @employee.update(employee_params)
      redirect_to employee_path(@employee)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @employee.destroy
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def myemployees
    @employees = Employee.where(user: current_user)
  end


  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :job_title, :description, :price_per_day)
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @employee = Employee.find(params[:employee_id])
    @Review = Review.new
  end

  def create

    @employee = Employee.find(params[:employee_id])
    @review = Review.new(review_params)
    @review.employee = @employee
    if @review.save!
       @employee.rating = average_rating(params[:review][:rating]);
       @employee.save
      redirect_to employee_path(@employee)
    else
      @review.save!
    end

  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def average_rating(actual_rating)
    reviews_employee = Review.where(employee: @employee)
    if reviews_employee
      count = 0
      reviews_employee.each do |review|
        count += review.rating
      end
      count / reviews_employee.size
    else
   actual_rating
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/historic.html.erb
<section class="form-page">

   <div class="container">
    <h2 ><span class="span-pink">Liste des réservations en cours</span></h2>
   <ul>
        <li class="grid-cards-column-name">
       <p class="child-element-column-name">Début de réservation</p>
       <p class="child-element-column-name">Fin de réservation</p>
       <p class="child-element-column-name">Prénom et nom</p>
       <p class="child-element-column-name">Job</p>
       <p class="child-element-column-name">Nombre de jours</p>
       <p class="child-element-column-name">Prix total</p>

    </li>
    <% @appointments.each do |appointment| %>
    <li class="grid-cards">
       <p class="child-element">
        <% date= appointment.debut_de_reservation.to_time %>
        <%= date.strftime("Du %d %B %Y") %>
        </p>
       <p class="child-element">
        <%date= appointment.fin_de_reservation %>
        <%= date.strftime("Au %d %B %Y") %>
       </p>
       <p class="child-element"><%= appointment.employee.first_name + "  " +appointment.employee.last_name %></p>
       <p class="child-element"><%= appointment.employee.job_title %></p>
       <p class="child-element"><%= appointment.renting_days %></p>
       <p class="child-element"><%= appointment.total_price %></p>
        <%= link_to "X", appointment_path(appointment), data: { turbo_method: "delete", turbo_confirm: "Êtes-vous vraiment vraiment sur?" }, class: "cancel" %>

           </li>
      <% end %>


    </div>
    </div>
</section>

app/views/appointments/index.html.erb
<%= @appointments.size %>

app/views/appointments/new.html.erb
<%= simple_form_for[@employee, @appointment] do |f| %>
<%= f.input total_price %>
<%= f.input renting_days %>
<%= f.submit "commander" %>
<% end %>

app/views/employees/_all_employees.html.erb
<section class="all-employees">

   <div class="container">
    <h2 ><span class="title">Nos employés</span></h2>
   <div class="cards">
    <% employees.each do |employee| %>
      <div class="card card-animate shadow">
        <div class="card-gradient">
          <div class="card-avatar">
            <% if employee.avatar.key != nil %>
            <%= cl_image_tag employee.avatar.key, width: 100, height: 100, crop: :fill %>
            <% end %>
          </div>
        </div>
        <div class="card-info">
          <p class="card-job"><%= employee.job_title %></p>
          <p class="card-description"><%= employee.description %></p>

<!-- Ajout fonctionnalité rating -->
          <p>
            <% if employee.rating %>
              <%employee.rating.times do %>
                <i class="fa-solid fa-star pink"></i>
              <% end %>(<%= employee.reviews.count %>)<% end %></p>
<!-- Fin Ajout fonctionnalité rating -->



          <p class="card-price"><span class="span-pink"><%= employee.price_per_day %> €</span></p>
          <%= link_to "Plus d'informations", employee_path(employee), class:"button-pink btn-center" %>
        </div>
      </div>
      <% end %>


    </div>
    </div>

         <%= image_tag "Image1.png", class:"bottom-image" %>


</section>

app/views/employees/_header.html.erb
<div class="header" data-controller="employe-roulette">
  <div class="modal-roulette">
      <div class="modal-roulette-content ">
        <h2><span class="title">Employé roulette!! Youhoou!</span></h2>
          <div class="random-job">
            <div class="triangle"></div>
              <div class="redirection-employee-roulette" data-action="click->employe-roulette#result">Valider ce choix</div>
          </div>
      </div>
  </div>
  <div class="container flex">
    <div class="header-title">


    <div class="header-title-logo">
        <%= image_tag "logo.png", class:"image-logo" %>
        <div class="empnloc">
          <h1 class="irish-grover-regular">Réserver votre <br>employé</h1>

          <p class="caveat">Trouver pour chaque situation une personne qualifiée comme

              un nettoyeur d'écrans de cinéma, un éleveur d’insectes,
               un gumoliste</p>
        </div>
      </div>

       <div id="employee_img"></div>
    </div>

    <div class="features-search">
      <form action="" class="form-search" data-action="submit->search#clear">
        <div class="input_search">
            <%= form_with url: employees_path, method: :get, class: "input-search" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Employé recherché",
                data: {action: "input->search#clear"}
              %>
        </div>
        <div class="input_search">
            <%= submit_tag "Rechercher", name: "", class: "button-pink card-animate" %>
            <% end %>
        </div>



      </form>
      <div class="block-center mt-5 " data-action="click->employe-roulette#modal"><span class="confetti-button animate shadow">Employés Roulette</span></div>
      </div>
    </div>



  </div>
</div>


<hr>

app/views/employees/_review.html.erb
    <ul class="reviews_list">
      <h3>Avis</h3>

      <% @reviews.each do |review| %>
      <li>
        <div class="reviews_list_inline">
          <% if review.rating != nil %>
            <% stars= review.rating  %>
            <% stars.times do  %>
             <i class="fa-solid fa-star pink"></i>
            <% end %>
          <% end %>
          <% time = Time.now %>
          <%resultat_time = ((time - review.created_at.to_time)/60).floor %>
          <% if resultat_time == 0 %>
          <span><%= "less than a minute" %></span>
          <% end %>
          <% if resultat_time > 0 && resultat_time < 60 %>
          <span><%= "there are #{resultat_time} minutes" %></span>
          <% end %>
          <% if resultat_time > 60 && resultat_time < 1440 %>
          <span><%= "there are  #{resultat_time/60} hours" %></span>
          <% end %>
          <% if resultat_time > 1440  %>
          <span><%= "there are  #{resultat_time/60/24} days" %></span>
          <% end %>


        </div>
        <p class="review_comment">
        <%= review.comment %>
        </p>
      </li>
      <% end %>
    </ul>

app/views/employees/_review_new.html.erb
<div class="review">
  <h3>Laissez votre avis</h3>
<%= simple_form_for [employee, review] do |f| %>
<%= f.input :comment  %>
<i class="fa-solid fa-star star" data-number="1"></i>
<i class="fa-solid fa-star star" data-number="2"></i>
<i class="fa-solid fa-star star" data-number="3"></i>
<i class="fa-solid fa-star star" data-number="4"></i>
<i class="fa-solid fa-star star" data-number="5"></i>
<%= f.hidden_field :rating, value: "valeur_masquée", class:"hidden_input" %>
<script>

  // Initialisation des variables
  stars = document.querySelectorAll('.fa-solid.fa-star.star');
  rating = document.querySelector('.hidden_input');

  // Display The correct number of yellow Stars
  function pinkStar(nb){
    stars.forEach((star, id) => {
      if (id < nb) {
      star.classList.add('pink');
      } else {
        star.classList.remove('pink');
      }
    })
  }
  stars.forEach((star) => {
    star.addEventListener('click', (e)=>{
      star.classList.toggle('pink');
      pinkStar(star.dataset.number);
      //return value rating
      rating.value = star.dataset.number;
    })
  })

    stars.forEach((star) => {
    star.addEventListener('mouveover', (e)=>{
      star.classList.toggle('pink');
      pinkStar(star.dataset.number);
      //return value rating
      rating.value = star.dataset.number;
    })
  })






</script>
<br>
<br>
<div class="flex">
<%= f.submit "Valider", class:"button-pink btn-center" %>
</div>
<% end %>

</div>

app/views/employees/_search_results.html.erb
<section class="search-results">

   <div class="container">
    <h2 ><span class="title">Résultat</span></h2>
   <div class="cards">
    <% employees.each do |employee| %>
      <div class="card card-animate shadow">
        <div class="card-gradient">
          <div class="card-avatar">
            <% if employee.avatar.key != nil %>
            <%= cl_image_tag employee.avatar.key, width: 100, height: 100, crop: :fill %>
            <% end %>
          </div>
        </div>
        <div class="card-info">
          <p class="card-job"><%= employee.job_title %></p>

<!-- Ajout fonctionnalité rating -->
          <%
          reviews_employee = Review.where(employee: employee.id)
          total_rating = 0
          if reviews_employee.present?
            reviews_employee.each do |review_employee|
              total_rating += review_employee.rating
            end
            average_rating = (total_rating / reviews_employee.count).round
          end
              if average_rating != nil
            average_rating.times do  %>
             <i class="fa-solid fa-star pink"></i>
            <% end
          end %>
<!-- Fin Ajout fonctionnalité rating -->

          <p class="card-price"><span class="span-pink"><%= employee.price_per_day %> €</span></p>
          <%= link_to "Plus d'informations", employee_path(employee), class:"button-pink btn-center" %>
        </div>
      </div>
      <% end %>


    </div>
    </div>
</section>

app/views/employees/_top.html.erb
<section class="top-employee">
  <div class="container">

    <h2><span class="title title_top" data-search-target ="title">Les tops employés</span></h2>
    <div class="cards">
       <%= image_tag "top_employee.png", class:"top-image" %>
     <% top_employees.each do |top_employee| %>
      <div class="card card-animate shadow">
        <div class="card-gradient">
          <div class="card-avatar">
            <%= cl_image_tag top_employee.avatar.key, width: 100, height: 100, crop: :fill %>
          </div>
        </div>
        <div class="card-info">
          <p class="card-job"><%= top_employee.job_title %></p>
 <p><% if top_employee.rating %>
 <%top_employee.rating.times do %>
 <i class="fa-solid fa-star pink"></i>
 <% end %>(<%= top_employee.reviews.count %>)
<% end %>
 </p>

 <!-- Fin Ajout fonctionnalité rating -->

          <p class="card-price"><span class="span-blue"><%= top_employee.price_per_day %> €</span></p>
          <%= link_to "Plus d'informations", employee_path(top_employee), class:"button-blue btn-center" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>
<hr id="pink">

app/views/employees/edit.html.erb
<div class="form-page">
  <div data-controller="select-image">
<div class="container flex">
<div class="form-container">
  <h2>Modifier votre employé</h2>
<%= simple_form_for(@employee) do |f| %>
  <%= f.input :first_name,input_html: { class: "input_search_form" } %>
  <%= f.input :last_name,input_html: { class: "input_search_form" }  %>
  <%= f.input :job_title,input_html: { class: "input_search_form" }  %>
  <%= f.input :description,input_html: { class: "input_search_form" }  %>
  <%= f.input :price_per_day,input_html: { class: "input_search_form" }  %>
  <%= f.input :avatar, as: :hidden, input_html: {id: 'selected-image'} %>
  <div data-select-image-target="displayElement" class="">
    <div class="card-avatar">
      <%= image_tag @employee.avatar, width: 150, height: 150, crop: :fill%>
    </div>
  </div>
  <%= f.submit "Valider",  class: "button-search-employee"  %>
<% end %>
</div>

  <div class="form-avatar">
    <div class="form-avatar-container">
      <h2>Choisissez votre avatar</h2>
      <div class="form-avatars-circle">
        <div data-action="click->select-image#pick">
          <div class="card-avatar">
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708507330/o8ow8hfqcksnspi8lkrt.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/qunltud7i9ctrha0eht2.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/xyzftalxipkduhr85yyk.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/ojwxvlbutx7vrrisclm4.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/e6w54g2pd0ilqvops64z.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/mrsixqzi4lqxmxgxm4du.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/vcvzgthnfo8guahny65k.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/fv24surswbq1s1tiqnqx.jpg", width: 150, height: 150, crop: :fill%>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%# <script>
        const avatar = document.querySelector(".avatar-circle")
        const container = document.querySelector(".form-avatars-circle")
        for (let i = 0; i < 12; i++) {
          const newAvatar = avatar.cloneNode(true);
          container.append(newAvatar);
        }
      </script> %>

</div>
</div>
</div>
</div>

</div>

app/views/employees/index.html.erb
<div data-controller="search">
<%= render "header"%>
<%= render "top", top_employees: @top_employees%>
<%= render "all_employees", employees: @employees%>
<%= render "search_results", employees: @employees%>
<%= render "/shared/footer"%>
</div>

app/views/employees/myemployees.html.erb
<section class="form-page">

   <div class="container">
    <h2 ><span class="span-pink">Liste de mes employés</span></h2>
   <div class="cards">
    <% @employees.each do |employee| %>
      <div class="card shadow dashed">
        <div class="card-gradient">
          <div class="card-avatar">
            <% if employee.avatar.key != nil %>
            <%= cl_image_tag employee.avatar.key, width: 100, height: 100, crop: :fill %>
            <% end %>
          </div>
        </div>
        <div class="card-info">
          <p class="card-job"><%= employee.job_title %></p>
          <p class="card-price">Prix:  <%= employee.price_per_day %></p>
          <div class="group-button">
          <%= link_to "Modifier", edit_employee_path(employee), class:"card-alink backgroundPink" %>
         <%= link_to "Supprimer", employee_path(employee), data: { turbo_method: "delete", turbo_confirm: "Êtes-vous vraiment vraiment sur?" }, class:"card-alink backgroundRed" %>

        </div>
        </div>
      </div>
      <% end %>


    </div>
    </div>
</section>

app/views/employees/new.html.erb
<div class="form-page">
<div data-controller="select-image">
<div class="container flex">
<div class="form-container">
  <h2>Créer votre employé</h2>
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>
  <%= f.input :first_name, input_html: { class: "input_search_form" } %>
  <%= f.input :last_name, input_html: { class: "input_search_form" }  %>
  <%= f.input :job_title, input_html: { class: "input_search_form" }  %>
  <%= f.input :description, input_html: { class: "input_search_form" }  %>
  <%= f.input :price_per_day, input_html: { class: "input_search_form" }  %>
  <%= f.input :avatar, as: :hidden, input_html: {id: 'selected-image'} %>
  <div data-select-image-target="displayElement" class="">
    <div class="card-avatar">
      <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708507330/o8ow8hfqcksnspi8lkrt.jpg", width: 150, height: 150, crop: :fill%>
    </div>
  </div>
  <%= f.button :submit, "Valider", class: "button-search-employee"  %>
  <% end %>
</div>
<div class="arrow"></div>

  <div class="form-avatar">
    <div class="form-avatar-container">
      <h2>Choisissez votre avatar</h2>
      <div class="form-avatars-circle">
        <div data-action="click->select-image#pick">
          <div class="card-avatar">
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708507330/o8ow8hfqcksnspi8lkrt.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/qunltud7i9ctrha0eht2.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/xyzftalxipkduhr85yyk.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/ojwxvlbutx7vrrisclm4.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/e6w54g2pd0ilqvops64z.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/mrsixqzi4lqxmxgxm4du.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/vcvzgthnfo8guahny65k.jpg", width: 150, height: 150, crop: :fill%>
                <%= image_tag "https://res.cloudinary.com/dvarz39fw/image/upload/v1708508011/fv24surswbq1s1tiqnqx.jpg", width: 150, height: 150, crop: :fill%>
              </div>
            </div>
          </div>
        </div>
      </div>



      <%# <script>
        const avatar = document.querySelector(".avatar-circle")
        const container = document.querySelector(".form-avatars-circle")
        for (let i = 0; i < 12; i++) {
          const newAvatar = avatar.cloneNode(true);
          container.append(newAvatar);
        }
      </script> %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empnloc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if user_signed_in? %>
  <p>Hello <%= current_user.email %></p>
<% else %>
  <p>You are not logged in</p>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
<div class="flex"><%= image_tag "logo.png", class:"logo-nav" %> <h2 class="pink" >empN'loc</h2></div>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Acceuil", root_path, class: "nav-link irish-grover-regular border-right nav_hover" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Créer votre employé", new_employee_path, class: "nav-link border-right irish-grover-regular nav_hover" %>
          </li>
          <!--<li class="nav-item ">
            <%= link_to "Logout", root_path, class: " nav-link button-pink " %>
          </li> -->
         <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="avatar-pink-circle"><i class="fa-solid fa-user"></i></div>
          </a>
            <div class="dropdown-menu dropdown-menu-end version-pink" aria-labelledby="navbarDropdown">
              <%= link_to "Gérer ses réservations", historic_appointments_path, class: "dropdown-item version-white" %>
              <%= link_to "Gérer ses employés", myemployees_employees_path, class: "dropdown-item version-white" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item version-white" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link button-pink " %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>